// import './js/program2.js';
// import './js/variables.js';
// import './js/primitives.js';
//import './js/toString.js';
//import './js/toNumber.js';
//import './js/boolean.js';
//import './js/false-variables.js';
//import './js/modul1.1.js';
//import './js/branching-operators.js';
//import './js/modul1.2.js';
import './js/modul2.1.js';
